import { Manrope } from "next/font/google";
import "./globals.css";
import { MantineProvider } from "@mantine/core";
import ClientLayout from "@/components/ClientLayout";

const manrope = Manrope({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
  display: "swap",
});

export const metadata = {
  title: "HireSphere",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${manrope.className} flex flex-col bg-primary-950`}>
        <MantineProvider>
         <ClientLayout>{children}</ClientLayout>
        </MantineProvider>
      </body>
    </html>
  );
}